name: Rpix Auto Update
on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت یکبار
  workflow_dispatch:
  repository_dispatch:
    types: [retry_run]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests

      - name: Run Script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add export/
          git commit -m "Sync: $(date)" || exit 0
          git push

      - name: Check Count and Retry
        run: |
          COUNT=$(cat count.txt)
          if [ "$COUNT" -lt 50 ]; then
            echo "Found $COUNT configs. Target is 50. Retrying in 5 minutes..."
            sleep 300
            curl -X POST -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "retry_run"}'
          else
            echo "Target reached: $COUNT configs."
          fi
